### PR TITLE
Fix ingestor

### LINKED ISSUE #195: Modify ingestor to read IdentifiedUnifiedItem from the SQS queue
The id minter sends identified unified items to the ingestor SNS topic. The ingestor expects unified items instead. Also, it filters messages based on the SNS subject the were published with and it expects subject "example" which is not the one used by the id minter and therefore all of the messages get discarded

### PR DESCRIPTION
**Pull request by alicefuzier**
## What is this PR trying to achieve?
Make the ingestor insert in elastic search items sent by the id minter. At the moment it rejects them as it only accepts messages with subject "example". Also, it expects SQS messages to contain a unified item, while they actually contain an identified unified item.  I also want to take the opportunity to refactor and introduce some tests
Resolves #195 

## Who is this change for?
Everyone who uses our platform

## Have the following been considered/are they needed?

- [x] Tests?
- [x] Docs?
- [x] Spoken to the right people?

### CODE REVIEW

File: common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala [hunk 1]
```diff
@@ -39,4 +43,31 @@ class SQSReader @Inject()(sqsClient: AmazonSQS, sqsConfig: SQSConfig)
...
+        Future.fromTry(Try(process(message))
+          .recover {
+            case e: Throwable =>
+              error(s"Error processing message", e)
+              throw e
+        }).flatMap(_ => deleteMessage(message))
+      })
+  }
+
+  private def deleteMessage(message: Message) =
```
Comment (alexwlchan) [inline common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala]: I think it would be helpful to explain the SQS concepts in a comment somewhere. What should the processor do? Why do we delete a message after we’ve processed it? What happens if we don’t?

(I’m happy to write this if you want, but _somebody_ should write something.)

File: common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala [hunk 2]
```diff
@@ -39,4 +43,31 @@ class SQSReader @Inject()(sqsClient: AmazonSQS, sqsConfig: SQSConfig)
...
+    Future {
+      blocking {
```
Comment (alexwlchan) [inline common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala]: Why are we blocking here?

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala [hunk 3]
```diff
@@ -15,44 +15,81 @@ class SQSReaderTest
...
 
+  override def queueName: String = "id_minter_queue"
+
   it("should get messages from the SQS queue, limited by the maximum number of messages and return them") {
     val sqsConfig =
-      SQSConfig("eu-west-1",
-                idMinterQueueUrl,
-                waitTime = 20 seconds,
-                maxMessages = 2)
+      SQSConfig("eu-west-1", queueUrl, waitTime = 20 seconds, maxMessages = 2)
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: I must have missed something – where is `queueUrl` defined?

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala [hunk 4]
```diff
@@ -15,44 +15,81 @@ class SQSReaderTest
...
     val messageStrings = List("someMessage1", "someMessage2", "someMessage3")
-    messageStrings.foreach(sqsClient.sendMessage(idMinterQueueUrl, _))
+    messageStrings.foreach(sqsClient.sendMessage(queueUrl, _))
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: Remind me what the second argument to this function is, and why we pass in `_`?

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala [hunk 5]
```diff
@@ -15,44 +15,81 @@ class SQSReaderTest
...
     val sqsReader =
       new SQSReader(sqsClient, sqsConfig)
 
-    val futureMessages = sqsReader.retrieveMessages()
+    var receivedMessages: List[Message] = Nil
 
-    whenReady(futureMessages) { messages =>
+    val futureMessages = sqsReader.retrieveAndDeleteMessages(message => receivedMessages = message :: receivedMessages)
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: What’s this line doing? (I’ve googled “Scala double colon operator”, but it’s not immediately obvious.)

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala [hunk 6]
```diff
@@ -15,44 +15,81 @@ class SQSReaderTest
...
+
+    whenReady(futureMessages) { _ =>
       // SQS is not a FIFO queue and it only guarantees that a message is sent at least once,
       // not that it is received exactly once
-      messages should have size 2
-      messages.foreach { message =>
+      receivedMessages should have size 2
+      receivedMessages.foreach { message =>
         messageStrings should contain(message.getBody)
       }
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: Now in fact we can go back to a slightly stronger assertion: the two messages should be _distinct_, because we delete them from the queue after processing.

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala [hunk 7]
```diff
@@ -15,44 +15,81 @@ class SQSReaderTest
...
     }
   }
 
-  private def createMessage(jsonMessage: String) =
-    new Message().withBody(jsonMessage)
+  it("should return a failed future if processing one of the messages fails - the failed message should not be deleted") {
+    val sqsConfig =
+      SQSConfig("eu-west-1", queueUrl, waitTime = 20 seconds, maxMessages = 10)
+
+    val failingMessage = "failingMessage"
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: Can we pick a string that’s different from the variable names? Makes logs easier to debug, because you can tell whether you’re looking at a traceback or an output. For example:

```scala
val failingMessage = "This message will fail"
val messageStrings = List("This is the first message", failingMessage, "This is the final message")
```

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala [hunk 8]
```diff
@@ -15,44 +15,81 @@ class SQSReaderTest
...
+        throw new RuntimeException(s"$failingMessage is not valid")
+      else message
+    }
+
+    whenReady(futureMessages.failed) { exception =>
+      exception shouldBe a[RuntimeException]
+    }
+
+    // Check that the queue still contains all 3 messages
+    assertNumberOfMessagesAfterVisibilityTimeoutIs(1, sqsReader)
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: Assertion doesn’t match the comment.

File: common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala [hunk 9]
```diff
@@ -16,12 +24,28 @@ trait SQSLocal extends Suite with BeforeAndAfterEach {
       new EndpointConfiguration(s"http://localhost:9324", "localhost"))
     .build()
 
-  val idMinterQueue = "es_id_minter_queue"
-  val idMinterQueueUrl = sqsClient.createQueue(idMinterQueue).getQueueUrl
+  def queueName: String
+
+  // Use eventually to allow some time for the local SQS to start up. Seems to be needed on CI
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala]: > Seems to be needed on CI

Can you be more specific? What do we see if we don't use `eventually`? Does it hang? Crash? Fail prematurely?

File: common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala [hunk 10]
```diff
@@ -16,12 +24,28 @@ trait SQSLocal extends Suite with BeforeAndAfterEach {
...
+  val queueUrl = eventually {
+    sqsClient.createQueue(queueName).getQueueUrl
+  }
+
+  // AWS does not delete a message automatically once it's read.
+  // It hides for the number of seconds specified in VisibilityTimeout.
+  // After the timeout has passet it will be sent again.
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala]: /s/passet/passed

File: common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala [hunk 11]
```diff
@@ -16,12 +24,28 @@ trait SQSLocal extends Suite with BeforeAndAfterEach {
...
+  // Setting 1 second timeout for tests, to be able to test message deletion
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala]: Yay! We should have a comment like this in SQSReader as well. And let’s make it clear that there’s an explicit delete step required from us. Something like:

> After a consumer reads a message from an SQS queue, AWS doesn’t delete the message immediately. It "hides" the message for a fixed period, until either
>
> 1. the consumer tells SQS to delete the message, or
> 2. the timeout expires
>
> If the timeout expires before the consumer sends a delete request, the message is unhidden and can be read by another consumer.

File: id_minter/src/test/scala/uk/ac/wellcome/platform/idminter/IdMinterIntegrationTest.scala [hunk 12]
```diff
@@ -14,21 +15,27 @@ import uk.ac.wellcome.models.{
...
-    extends IntegrationTestBase
+    extends IntegrationTest
+    with SQSLocal
+    with DynamoDBLocal
+    with SNSLocal
     with Eventually
     with IntegrationPatience {
 
+  override def topicName: String = "ingester"
+  override def queueName: String = "id_minter"
```
Comment (alexwlchan) [inline id_minter/src/test/scala/uk/ac/wellcome/platform/idminter/IdMinterIntegrationTest.scala]: Let's prefix these with `test_` so we can't get confused with the prod instances.

File: ingestor/src/main/scala/uk/ac/wellcome/platform/ingestor/services/IdentifiedUnifiedItemIndexer.scala [hunk 13]
```diff
@@ -0,0 +1,40 @@
...
+      .fromTry(JsonUtil.fromJson[IdentifiedUnifiedItem](document))
+      .flatMap(item => {
+        info(s"Indexing item $item")
+        elasticClient.execute {
+          indexInto(esIndex / esType).doc(item)
+        }
+      })
+      .recover {
+        case e: Throwable =>
+          error(s"error indexing document $document into elasticsearch", e)
```
Comment (alexwlchan) [inline ingestor/src/main/scala/uk/ac/wellcome/platform/ingestor/services/IdentifiedUnifiedItemIndexer.scala]: nit: Sentences start with a capital letter, and so should "elasticsearch".

File: ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/ElasticSearchLocal.scala [hunk 14]
```diff
@@ -0,0 +1,46 @@
...
+    .builder()
+    .put("cluster.name", "wellcome")
+    .put("xpack.security.user", "elastic:changeme")
+    .build()
+
+  val elasticClient =
+    XPackElasticClient(settings, ElasticsearchClientUri("localhost", 9300))
+
+  override def beforeAll(): Unit = {
+    // Elastic search takes a while to start up so check that it actually started before running tests
```
Comment (alexwlchan) [inline ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/ElasticSearchLocal.scala]: nit: /s/Elastic search/Elasticsearch

File: ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/IngestorIntegrationTest.scala [hunk 15]
```diff
@@ -0,0 +1,80 @@
...
+import uk.ac.wellcome.utils.GlobalExecutionContext.context
+import uk.ac.wellcome.utils.JsonUtil
+
+class IngestorIntegrationTest
+    extends IntegrationTest
+    with SQSLocal
+    with Matchers
+    with ElasticSearchLocal {
+
+  override def queueName: String = "es_ingestor_queue"
```
Comment (alexwlchan) [inline ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/IngestorIntegrationTest.scala]: `test_es_ingestor_queue`.

File: ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/IngestorIntegrationTest.scala [hunk 16]
```diff
@@ -0,0 +1,80 @@
...
+
+  override def injector: Injector =
+    TestInjector(
+      flags = Map(
+        "aws.region" -> "eu-west-1",
+        "aws.sqs.queue.url" -> queueUrl,
+        "aws.sqs.waitTime" -> "1",
+        "es.host" -> "localhost",
+        "es.port" -> 9300.toString,
```
Comment (alexwlchan) [inline ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/IngestorIntegrationTest.scala]: Why not just `"9300"`?

File: common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala (hunk 1 above)
Comment (alicefuzier) [inline common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala]: Right, I think I added it in SQSLocal, but maybe that's not the right place, it's too hidden

File: common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala (hunk 2 above)
Comment (alicefuzier) [inline common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala]: We're not. As far as I understood is a way of saying to the execution context that the enclosed code is blocking, so that the execution context can deal with it

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala (hunk 3 above)
Comment (alicefuzier) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: It in SQSLocal. It is defined based on queueName

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala (hunk 4 above)
Comment (alicefuzier) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: When you define a function that takes only one argument you can use this shortened syntax where the underscore represents the only argument of your function. Basically that is the same as
```
messageStrings.foreach( messageString=>sqsClient.sendMessage(queueUrl, messageString) 
```

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala (hunk 5 above)
Comment (alicefuzier) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: It's prepending to the receivedMessages list. Functions staring with semicolon in Scala are evaluated from the right. So actually ```::``` is a function defined on ```List``` that prepends messages and that line really means 
```
receivedMessages.::(message)
```

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala (hunk 6 above)
Comment (alicefuzier) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: Right I'll do that

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala (hunk 7 above)
Comment (alicefuzier) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: Right

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala (hunk 8 above)
Comment (alicefuzier) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: Oops, that is one of the reasons I don't like comments. I'll write a self explanatory name for that assertion and delete the comment

File: common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala (hunk 9 above)
Comment (alicefuzier) [inline common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala]: Crash. Yep, I'll add that

File: common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala [hunk 17]
```diff
@@ -1,28 +1,37 @@
...
+import scala.concurrent.{Future, blocking}
+import scala.util.{Failure, Success, Try}
 
 class SQSReader @Inject()(sqsClient: AmazonSQS, sqsConfig: SQSConfig)
     extends Logging {
+  // After a consumer reads a message from an SQS queue, AWS doesn’t delete the message immediately.
+  // It "hides" the message for a fixed period, until either
+  //  * the consumer tells SQS to delete the message, or
+  //  * the timeout expires
+  // If the timeout expires before the consumer sends a delete request, the message is unhidden and can be read by another consumer.
```
Comment (alexwlchan) [inline common/src/main/scala/uk/ac/wellcome/sqs/SQSReader.scala]: 👍

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala (hunk 6 above)
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: Let’s also expand the comment on L33-4 to explain what we're doing.

File: common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala [hunk 18]
```diff
@@ -15,44 +15,80 @@ class SQSReaderTest
...
   }
 
-  private def createMessage(jsonMessage: String) =
-    new Message().withBody(jsonMessage)
+  it("should return a failed future if processing one of the messages fails - the failed message should not be deleted") {
+    val sqsConfig =
+      SQSConfig("eu-west-1", queueUrl, waitTime = 20 seconds, maxMessages = 10)
+
+    val failingMessage = "This message will fail"
+    val messageStrings = List("This is the first message", failingMessage, "This is the final message")
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/sqs/SQSReaderTest.scala]: 👍

File: common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala [hunk 19]
```diff
@@ -16,12 +24,27 @@ trait SQSLocal extends Suite with BeforeAndAfterEach {
       new EndpointConfiguration(s"http://localhost:9324", "localhost"))
     .build()
 
-  val idMinterQueue = "es_id_minter_queue"
-  val idMinterQueueUrl = sqsClient.createQueue(idMinterQueue).getQueueUrl
+  def queueName: String
+
+  // Use eventually to allow some time for the local SQS to start up.
+  // If it is not started all suites using this will crash at start up time.
+  // Did not happen locally but seems to be needed on CI
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala]: 👍 Let’s be really explicit about the CI suite:

> In Travis, if the suites start before SQS is running, tests will crash at startup.

File: docker-compose.yml [hunk 20]
```diff
@@ -9,4 +9,13 @@ sns:
...
-    - "9324:9324"
\ No newline at end of file
+    - "9324:9324"
+elasticsearch:
+  image: docker.elastic.co/elasticsearch/elasticsearch:5.2.0
+  ports:
+    - "9200:9200"
+    - "9300:9300"
+  environment:
+      - "http.host=0.0.0.0"
```
Comment (alexwlchan) [inline docker-compose.yml]: nit: indentation is inconsistent

File: docker-compose.yml [hunk 21]
```diff
@@ -9,4 +9,13 @@ sns:
...
+      - "transport.host=0.0.0.0"
+      - "cluster.name=wellcome"
```
Comment (alexwlchan) [inline docker-compose.yml]: nit: files should have a trailing newline

File: id_minter/src/test/scala/uk/ac/wellcome/platform/idminter/IdMinterIntegrationTest.scala [hunk 22]
```diff
@@ -14,21 +15,27 @@ import uk.ac.wellcome.models.{
...
 class IdMinterIntegrationTest
-    extends IntegrationTestBase
+    extends IntegrationTest
+    with SQSLocal
+    with DynamoDBLocal
+    with SNSLocal
     with Eventually
     with IntegrationPatience {
 
+  override def topicName: String = "test_ingester"
```
Comment (alexwlchan) [inline id_minter/src/test/scala/uk/ac/wellcome/platform/idminter/IdMinterIntegrationTest.scala]: nit: /s/ingester/ingestor

File: ingestor/src/main/scala/uk/ac/wellcome/platform/ingestor/modules/SQSWorker.scala [hunk 23]
```diff
@@ -0,0 +1,53 @@
...
+
+object SQSWorker extends TwitterModule with TryBackoff {
+  private val esIndex = flag[String]("es.index", "records", "ES index name")
+  private val esType = flag[String]("es.type", "item", "ES document type")
+
+  override def singletonStartup(injector: Injector) {
+    info("Starting SQS worker")
+
+    val system = injector.instance[ActorSystem]
+
```
Comment (alexwlchan) [inline ingestor/src/main/scala/uk/ac/wellcome/platform/ingestor/modules/SQSWorker.scala]: nit: lose the newline

File: ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/IngestorIntegrationTest.scala [hunk 24]
```diff
@@ -0,0 +1,80 @@
...
+      ),
+      modules = Seq(SQSConfigModule,
+                    AkkaModule,
+                    SQSReaderModule,
+                    SQSWorker,
+                    SQSLocalClientModule,
+                    ElasticClientModule)
+    )
+
+  test("it should read an identified unified item from the SQS queue and ingest it into elastic search") {
```
Comment (alexwlchan) [inline ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/IngestorIntegrationTest.scala]: nit: /s/elastic search/Elasticsearch

File: ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/IngestorIntegrationTest.scala [hunk 25]
```diff
@@ -0,0 +1,80 @@
...
+                     "timestamp"))
+        .get
+    )
+
+    SQSWorker.singletonStartup(injector)
+
+    eventually {
+      val hits =
+        elasticClient
+          .execute(search("records/item").matchAll())
```
Comment (alexwlchan) [inline ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/IngestorIntegrationTest.scala]: Use variables from the flags rather than repeating the index/document names?

File: ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/services/IdentifiedUnifiedItemIndexerTest.scala [hunk 26]
```diff
@@ -0,0 +1,54 @@
...
+import uk.ac.wellcome.utils.GlobalExecutionContext.context
+import uk.ac.wellcome.utils.JsonUtil
+
+class IdentifiedUnifiedItemIndexerTest
+    extends FunSpec
+    with ScalaFutures
+    with Matchers
+    with ElasticSearchLocal {
+
+  it("should insert an identified unified item into elastic search") {
```
Comment (alexwlchan) [inline ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/services/IdentifiedUnifiedItemIndexerTest.scala]: ditto

File: ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/services/IdentifiedUnifiedItemIndexerTest.scala [hunk 27]
```diff
@@ -0,0 +1,54 @@
...
+    val identifiedUnifiedItemIndexer =
+      new IdentifiedUnifiedItemIndexer("records", "item", elasticClient)
```
Comment (alexwlchan) [inline ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/services/IdentifiedUnifiedItemIndexerTest.scala]: ditto

File: common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala (hunk 19 above)
Comment (alicefuzier) [inline common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala]: I don't think this is really related to Travis, it could affect any CI and in fact even a slower local development machine

File: ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/services/IdentifiedUnifiedItemIndexerTest.scala [hunk 28]
```diff
@@ -0,0 +1,56 @@
...
+        hits should have size 1
+        hits.head.sourceAsString shouldBe identifiedUnifiedItemString
+      }
+    }
+
+  }
+
+  it("should return a failed future if the input string is not an identified unified item") {
+    val identifiedUnifiedItemIndexer =
+      new IdentifiedUnifiedItemIndexer("records", "item", elasticClient)
```
Comment (alexwlchan) [inline ingestor/src/test/scala/uk/ac/wellcome/platform/ingestor/services/IdentifiedUnifiedItemIndexerTest.scala]: Use variables here as well?

File: common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala [hunk 29]
```diff
@@ -16,12 +24,26 @@ trait SQSLocal extends Suite with BeforeAndAfterEach {
...
-  val idMinterQueueUrl = sqsClient.createQueue(idMinterQueue).getQueueUrl
+  def queueName: String
+
+  // Use eventually to allow some time for the local SQS to start up.
+  // If it is not started all suites using this will crash at start up time.
+  val queueUrl = eventually {
+    sqsClient.createQueue(queueName).getQueueUrl
+  }
+
+  // Setting 1 second timeout for tests, to be able to test message deletion
```
Comment (alexwlchan) [inline common/src/test/scala/uk/ac/wellcome/test/utils/SQSLocal.scala]: I’m not sure this follows. Couldn’t we test message deletion just as easily with a 15-second (I think that’s the default?) timeout by just waiting a bit longer? Or does the VisibilityTimeout default to infinity with our SQS local container?
